service: html-pdf-s3-upload
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  profile: sezer-admin
  region: ${opt:region, 'eu-central-1'}
  endpointType: REGIONAL
  stage: ${opt:stage, 'dev'}
  lambdaHashingVersion: 20201221
  apiGateway:
    binaryMediaTypes:
      - '*/*'
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    bucketName: ${self:custom.bucketName}

  iam:
    role:
      name: s3-role
      statements:
        - Effect: 'Allow'
          Resource: '*'
          Action:
            - 's3:getObject'

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-prune-plugin

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  prune:
    automatic: true
    number: 5
  bucketName: emails-1213123123121

functions:
  getPDF:
    handler: handler.getPDF
    memorySize: 1024
    events:
      - http:
          method: post
          path: /pdf/link

resources:
  Resources:
    DemoBucketUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
